### ISSUE TITLE
Replace IEventBroadcaster with an interface for a resolved object

### ISSUE THREAD

**Issue by a-vzhik** [tst-devs/UriShell#4]
Originally UriShell was a part of the big project and usage of IEventBroadcaster was reasonable.
As a separate library UriShell doesn't need a dedicated service for dispatching global events so IEventBroadcaster should be replaced with an interface for a resolved object.

**Comment by mxmsk** [comment]
Done. IEventBroadcaster was removed, IRefreshable was added. An interface with the same name already exists in WinRT, maybe we should switch to it in a future.
